"""add effective dates, status, deleted_by to party

Revision ID: 7f0446b3efb9
Revises: 6c66ed4bc608
Create Date: 2026-04-01 16:50:55.056453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f0446b3efb9'
down_revision: Union[str, Sequence[str], None] = '6c66ed4bc608'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party', sa.Column('effective_start_date', sa.Date(), nullable=True))
    op.add_column('party', sa.Column('effective_end_date', sa.Date(), nullable=True))
    op.add_column('party', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('party', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('party', 'deleted_by')
    op.drop_column('party', 'status')
    op.drop_column('party', 'effective_end_date')
    op.drop_column('party', 'effective_start_date')
    # ### end Alembic commands ###
